#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.7.0
// Descriptor size: 600 (bytes)
// +----------+---------+-------------------+
// | ReportId | Kind    | ReportSizeInBytes |
// +----------+---------+-------------------+
// |        1 | Input   |                24 |
// +----------+---------+-------------------+
// |        2 | Input   |                 1 |
// +----------+---------+-------------------+
// |        3 | Input   |                 8 |
// +----------+---------+-------------------+
// |        4 | Feature |                 1 |
// +----------+---------+-------------------+
// |        5 | Feature |               256 |
// +----------+---------+-------------------+
// |        6 | Feature |                 1 |
// +----------+---------+-------------------+
// |        7 | Feature |                 1 |
// +----------+---------+-------------------+
// |        8 | Input   |                 5 |
// +----------+---------+-------------------+
// |        9 | Feature |                 2 |
// +----------+---------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x0D,                      // UsagePage(Digitizers[0x000D])
    0x09, 0x05,                      // UsageId(Touch Pad[0x0005])
    0xA1, 0x01,                      // Collection(Application)
    0x85, 0x01,                      //     ReportId(1)
    0x09, 0x22,                      //     UsageId(Finger[0x0022])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x47,                      //         UsageId(Touch Valid[0x0047])
    0x09, 0x42,                      //         UsageId(Tip Switch[0x0042])
    0x15, 0x00,                      //         LogicalMinimum(0)
    0x25, 0x01,                      //         LogicalMaximum(1)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x01,                      //         ReportSize(1)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x51,                      //         UsageId(Contact Identifier[0x0051])
    0x25, 0x04,                      //         LogicalMaximum(4)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x03,                      //         ReportSize(3)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x81, 0x03,                      //         Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,                      //         UsagePage(Generic Desktop[0x0001])
    0x09, 0x30,                      //         UsageId(X[0x0030])
    0x46, 0xF5, 0x00,                //         PhysicalMaximum(245)
    0x65, 0x13,                      //         Unit('hundredths_inch', EnglishLinear, Inch:1)
    0x55, 0x0E,                      //         UnitExponent(0.01)
    0x26, 0xFF, 0x0F,                //         LogicalMaximum(4,095)
    0x75, 0x0C,                      //         ReportSize(12)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x31,                      //         UsageId(Y[0x0031])
    0x46, 0xC6, 0x00,                //         PhysicalMaximum(198)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0x05, 0x0D,                      //     UsagePage(Digitizers[0x000D])
    0x09, 0x22,                      //     UsageId(Finger[0x0022])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x47,                      //         UsageId(Touch Valid[0x0047])
    0x09, 0x42,                      //         UsageId(Tip Switch[0x0042])
    0x45, 0x00,                      //         PhysicalMaximum(0)
    0x65, 0x00,                      //         Unit(None)
    0x55, 0x00,                      //         UnitExponent(1)
    0x25, 0x01,                      //         LogicalMaximum(1)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x01,                      //         ReportSize(1)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x51,                      //         UsageId(Contact Identifier[0x0051])
    0x25, 0x04,                      //         LogicalMaximum(4)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x03,                      //         ReportSize(3)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x81, 0x03,                      //         Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,                      //         UsagePage(Generic Desktop[0x0001])
    0x09, 0x30,                      //         UsageId(X[0x0030])
    0x46, 0xF5, 0x00,                //         PhysicalMaximum(245)
    0x65, 0x13,                      //         Unit('hundredths_inch', EnglishLinear, Inch:1)
    0x55, 0x0E,                      //         UnitExponent(0.01)
    0x26, 0xFF, 0x0F,                //         LogicalMaximum(4,095)
    0x75, 0x0C,                      //         ReportSize(12)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x31,                      //         UsageId(Y[0x0031])
    0x46, 0xC6, 0x00,                //         PhysicalMaximum(198)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0x05, 0x0D,                      //     UsagePage(Digitizers[0x000D])
    0x09, 0x22,                      //     UsageId(Finger[0x0022])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x47,                      //         UsageId(Touch Valid[0x0047])
    0x09, 0x42,                      //         UsageId(Tip Switch[0x0042])
    0x45, 0x00,                      //         PhysicalMaximum(0)
    0x65, 0x00,                      //         Unit(None)
    0x55, 0x00,                      //         UnitExponent(1)
    0x25, 0x01,                      //         LogicalMaximum(1)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x01,                      //         ReportSize(1)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x51,                      //         UsageId(Contact Identifier[0x0051])
    0x25, 0x04,                      //         LogicalMaximum(4)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x03,                      //         ReportSize(3)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x81, 0x03,                      //         Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,                      //         UsagePage(Generic Desktop[0x0001])
    0x09, 0x30,                      //         UsageId(X[0x0030])
    0x46, 0xF5, 0x00,                //         PhysicalMaximum(245)
    0x65, 0x13,                      //         Unit('hundredths_inch', EnglishLinear, Inch:1)
    0x55, 0x0E,                      //         UnitExponent(0.01)
    0x26, 0xFF, 0x0F,                //         LogicalMaximum(4,095)
    0x75, 0x0C,                      //         ReportSize(12)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x31,                      //         UsageId(Y[0x0031])
    0x46, 0xC6, 0x00,                //         PhysicalMaximum(198)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0x05, 0x0D,                      //     UsagePage(Digitizers[0x000D])
    0x09, 0x22,                      //     UsageId(Finger[0x0022])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x47,                      //         UsageId(Touch Valid[0x0047])
    0x09, 0x42,                      //         UsageId(Tip Switch[0x0042])
    0x45, 0x00,                      //         PhysicalMaximum(0)
    0x65, 0x00,                      //         Unit(None)
    0x55, 0x00,                      //         UnitExponent(1)
    0x25, 0x01,                      //         LogicalMaximum(1)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x01,                      //         ReportSize(1)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x51,                      //         UsageId(Contact Identifier[0x0051])
    0x25, 0x04,                      //         LogicalMaximum(4)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x03,                      //         ReportSize(3)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x81, 0x03,                      //         Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,                      //         UsagePage(Generic Desktop[0x0001])
    0x09, 0x30,                      //         UsageId(X[0x0030])
    0x46, 0xF5, 0x00,                //         PhysicalMaximum(245)
    0x65, 0x13,                      //         Unit('hundredths_inch', EnglishLinear, Inch:1)
    0x55, 0x0E,                      //         UnitExponent(0.01)
    0x26, 0xFF, 0x0F,                //         LogicalMaximum(4,095)
    0x75, 0x0C,                      //         ReportSize(12)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x31,                      //         UsageId(Y[0x0031])
    0x46, 0xC6, 0x00,                //         PhysicalMaximum(198)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0x05, 0x0D,                      //     UsagePage(Digitizers[0x000D])
    0x09, 0x22,                      //     UsageId(Finger[0x0022])
    0xA1, 0x02,                      //     Collection(Logical)
    0x09, 0x47,                      //         UsageId(Touch Valid[0x0047])
    0x09, 0x42,                      //         UsageId(Tip Switch[0x0042])
    0x45, 0x00,                      //         PhysicalMaximum(0)
    0x65, 0x00,                      //         Unit(None)
    0x55, 0x00,                      //         UnitExponent(1)
    0x25, 0x01,                      //         LogicalMaximum(1)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x01,                      //         ReportSize(1)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x51,                      //         UsageId(Contact Identifier[0x0051])
    0x25, 0x04,                      //         LogicalMaximum(4)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x03,                      //         ReportSize(3)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x81, 0x03,                      //         Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,                      //         UsagePage(Generic Desktop[0x0001])
    0x09, 0x30,                      //         UsageId(X[0x0030])
    0x46, 0xF5, 0x00,                //         PhysicalMaximum(245)
    0x65, 0x13,                      //         Unit('hundredths_inch', EnglishLinear, Inch:1)
    0x55, 0x0E,                      //         UnitExponent(0.01)
    0x26, 0xFF, 0x0F,                //         LogicalMaximum(4,095)
    0x75, 0x0C,                      //         ReportSize(12)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x31,                      //         UsageId(Y[0x0031])
    0x46, 0xC6, 0x00,                //         PhysicalMaximum(198)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0x05, 0x0D,                      //     UsagePage(Digitizers[0x000D])
    0x09, 0x56,                      //     UsageId(Scan Time[0x0056])
    0x47, 0xFF, 0xFF, 0x00, 0x00,    //     PhysicalMaximum(65,535)
    0x66, 0x01, 0x10,                //     Unit('scan_time_unit', SiLinear, Seconds:1)
    0x55, 0x0C,                      //     UnitExponent(0.0001)
    0x27, 0xFF, 0xFF, 0x00, 0x00,    //     LogicalMaximum(65,535)
    0x75, 0x10,                      //     ReportSize(16)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x54,                      //     UsageId(Contact Count[0x0054])
    0x45, 0x00,                      //     PhysicalMaximum(0)
    0x65, 0x00,                      //     Unit(None)
    0x55, 0x00,                      //     UnitExponent(1)
    0x25, 0x05,                      //     LogicalMaximum(5)
    0x75, 0x03,                      //     ReportSize(3)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x05,                      //     ReportSize(5)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,                      //     UsagePage(Button[0x0009])
    0x09, 0x01,                      //     UsageId(Button 1[0x0001])
    0x25, 0x01,                      //     LogicalMaximum(1)
    0x75, 0x01,                      //     ReportSize(1)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x07,                      //     ReportSize(7)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x85, 0x09,                      //     ReportId(9)
    0x05, 0x0D,                      //     UsagePage(Digitizers[0x000D])
    0x09, 0x55,                      //     UsageId(Contact Count Maximum[0x0055])
    0x25, 0x05,                      //     LogicalMaximum(5)
    0x75, 0x03,                      //     ReportSize(3)
    0xB1, 0x02,                      //     Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x75, 0x05,                      //     ReportSize(5)
    0xB1, 0x03,                      //     Feature(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x09, 0x59,                      //     UsageId(Pad Type[0x0059])
    0x25, 0x01,                      //     LogicalMaximum(1)
    0x75, 0x01,                      //     ReportSize(1)
    0xB1, 0x02,                      //     Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x75, 0x07,                      //     ReportSize(7)
    0xB1, 0x03,                      //     Feature(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x85, 0x06,                      //     ReportId(6)
    0x09, 0x60,                      //     UsageId(Latency Mode[0x0060])
    0x75, 0x01,                      //     ReportSize(1)
    0xB1, 0x02,                      //     Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x75, 0x07,                      //     ReportSize(7)
    0xB1, 0x03,                      //     Feature(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                            // EndCollection()
    0x09, 0x0E,                      // UsageId(Device Configuration[0x000E])
    0xA1, 0x01,                      // Collection(Application)
    0x85, 0x05,                      //     ReportId(5)
    0x06, 0x00, 0xFF,                //     UsagePage(PTPHQA Page[0xFF00])
    0x09, 0xC5,                      //     UsageId(PTPHQA Blob[0x00C5])
    0x26, 0xFF, 0x00,                //     LogicalMaximum(255)
    0x96, 0x00, 0x01,                //     ReportCount(256)
    0x75, 0x08,                      //     ReportSize(8)
    0xB1, 0x02,                      //     Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x85, 0x04,                      //     ReportId(4)
    0x05, 0x0D,                      //     UsagePage(Digitizers[0x000D])
    0x09, 0x52,                      //     UsageId(Device Mode[0x0052])
    0x25, 0x0A,                      //     LogicalMaximum(10)
    0x95, 0x01,                      //     ReportCount(1)
    0x75, 0x04,                      //     ReportSize(4)
    0xB1, 0x02,                      //     Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xB1, 0x03,                      //     Feature(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x85, 0x07,                      //     ReportId(7)
    0x09, 0x57,                      //     UsageId(Surface Switch[0x0057])
    0x09, 0x58,                      //     UsageId(Button Switch[0x0058])
    0x25, 0x01,                      //     LogicalMaximum(1)
    0x95, 0x02,                      //     ReportCount(2)
    0x75, 0x01,                      //     ReportSize(1)
    0xB1, 0x02,                      //     Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x95, 0x01,                      //     ReportCount(1)
    0x75, 0x06,                      //     ReportSize(6)
    0xB1, 0x03,                      //     Feature(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                            // EndCollection()
    0x05, 0x01,                      // UsagePage(Generic Desktop[0x0001])
    0x09, 0x02,                      // UsageId(Mouse[0x0002])
    0xA1, 0x01,                      // Collection(Application)
    0x85, 0x08,                      //     ReportId(8)
    0x09, 0x01,                      //     UsageId(Pointer[0x0001])
    0xA1, 0x00,                      //     Collection(Physical)
    0x05, 0x09,                      //         UsagePage(Button[0x0009])
    0x19, 0x01,                      //         UsageIdMin(Button 1[0x0001])
    0x29, 0x02,                      //         UsageIdMax(Button 2[0x0002])
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x01,                      //         ReportSize(1)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,                      //         ReportCount(1)
    0x75, 0x06,                      //         ReportSize(6)
    0x81, 0x03,                      //         Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,                      //         UsagePage(Generic Desktop[0x0001])
    0x09, 0x30,                      //         UsageId(X[0x0030])
    0x09, 0x31,                      //         UsageId(Y[0x0031])
    0x16, 0x01, 0x80,                //         LogicalMinimum(-32,767)
    0x26, 0xFF, 0x7F,                //         LogicalMaximum(32,767)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x10,                      //         ReportSize(16)
    0x81, 0x06,                      //         Input(Data, Variable, Relative, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0xC0,                            // EndCollection()
    0x05, 0x0C,                      // UsagePage(Consumer[0x000C])
    0x09, 0x01,                      // UsageId(Consumer Control[0x0001])
    0xA1, 0x01,                      // Collection(Application)
    0x85, 0x02,                      //     ReportId(2)
    0x09, 0xCD,                      //     UsageId(Play/Pause[0x00CD])
    0x09, 0xB5,                      //     UsageId(Scan Next Track[0x00B5])
    0x09, 0xB6,                      //     UsageId(Scan Previous Track[0x00B6])
    0x09, 0xE9,                      //     UsageId(Volume Increment[0x00E9])
    0x09, 0xEA,                      //     UsageId(Volume Decrement[0x00EA])
    0x09, 0xE2,                      //     UsageId(Mute[0x00E2])
    0x15, 0x00,                      //     LogicalMinimum(0)
    0x25, 0x01,                      //     LogicalMaximum(1)
    0x95, 0x06,                      //     ReportCount(6)
    0x75, 0x01,                      //     ReportSize(1)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,                      //     ReportCount(1)
    0x75, 0x02,                      //     ReportSize(2)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            // EndCollection()
    0x05, 0x01,                      // UsagePage(Generic Desktop[0x0001])
    0x09, 0x06,                      // UsageId(Keyboard[0x0006])
    0xA1, 0x01,                      // Collection(Application)
    0x85, 0x03,                      //     ReportId(3)
    0x05, 0x07,                      //     UsagePage(Keyboard/Keypad[0x0007])
    0x19, 0xE0,                      //     UsageIdMin(Keyboard LeftControl[0x00E0])
    0x29, 0xE7,                      //     UsageIdMax(Keyboard Right GUI[0x00E7])
    0x95, 0x08,                      //     ReportCount(8)
    0x75, 0x01,                      //     ReportSize(1)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,                      //     ReportCount(1)
    0x75, 0x08,                      //     ReportSize(8)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x19, 0x01,                      //     UsageIdMin(ErrorRollOver[0x0001])
    0x29, 0x65,                      //     UsageIdMax(Keyboard Application[0x0065])
    0x15, 0x01,                      //     LogicalMinimum(1)
    0x25, 0x65,                      //     LogicalMaximum(101)
    0x95, 0x06,                      //     ReportCount(6)
    0x75, 0x07,                      //     ReportSize(7)
    0x81, 0x00,                      //     Input(Data, Array, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,                      //     ReportCount(1)
    0x75, 0x06,                      //     ReportSize(6)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId = HID_REPORT_INPUT1_ID;
    uint8_t Payload[24];
};

#define HID_REPORT_FEATURE9_ID (9)
struct HidReportFeature9
{
    uint8_t ReportId = HID_REPORT_FEATURE9_ID;
    uint8_t Payload[2];
};

#define HID_REPORT_FEATURE6_ID (6)
struct HidReportFeature6
{
    uint8_t ReportId = HID_REPORT_FEATURE6_ID;
    uint8_t Payload[1];
};

#define HID_REPORT_FEATURE5_ID (5)
struct HidReportFeature5
{
    uint8_t ReportId = HID_REPORT_FEATURE5_ID;
    uint8_t Payload[256];
};

#define HID_REPORT_FEATURE4_ID (4)
struct HidReportFeature4
{
    uint8_t ReportId = HID_REPORT_FEATURE4_ID;
    uint8_t Payload[1];
};

#define HID_REPORT_FEATURE7_ID (7)
struct HidReportFeature7
{
    uint8_t ReportId = HID_REPORT_FEATURE7_ID;
    uint8_t Payload[1];
};

#define HID_REPORT_INPUT8_ID (8)
struct HidReportInput8
{
    uint8_t ReportId = HID_REPORT_INPUT8_ID;
    uint8_t Payload[5];
};

#define HID_REPORT_INPUT2_ID (2)
struct HidReportInput2
{
    uint8_t ReportId = HID_REPORT_INPUT2_ID;
    uint8_t Payload[1];
};

#define HID_REPORT_INPUT3_ID (3)
struct HidReportInput3
{
    uint8_t ReportId = HID_REPORT_INPUT3_ID;
    uint8_t Payload[8];
};

#pragma pack(pop)